# Production PostgreSQL Configuration
production:
  adapter: postgis
  encoding: unicode
  url: postgresql://postgres:QNLpCHrVBDEckrVuesjNQSGDVRHvShqa@ballast.proxy.rlwy.net:12444/railway
  pool: 5
  schema_search_path: "public,postgis"
